apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: nimtechnology
  includeCRDs: false
  releaseName: workload1
  version: 0.1.2 #look at
  repo: https://raw.githubusercontent.com/mrnim94/kubernetes-manifest/master/
  valuesFile: values_helm.yaml
  namespace: default
images:
- name: 250887682577.dkr.ecr.us-east-1.amazonaws.com/demo-codebuild
  newTag: build-9f573647-d848-4a98-895f-927c85886572
