apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: nimtechnology
  includeCRDs: false
  releaseName: workload1
  version: 0.1.1 #look at
  repo: https://raw.githubusercontent.com/mrnim94/kubernetes-manifest/master/
  valuesFile: values_helm.yaml
  namespace: default
images:
- name: nginx
  newTag: 1.23.1